version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "6500:6500"
    image: app:server
    container_name: node-app
    command: npm start
